# Generated by Django 3.0.4 on 2020-03-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('foto', models.ImageField(upload_to='img', verbose_name='Foto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
