# Generated by Django 3.0.4 on 2020-03-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200323_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Foto'),
        ),
    ]
