# Generated by Django 3.0.4 on 2020-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200323_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='../static/img/defaut.png', null=True, upload_to='img', verbose_name='Foto'),
        ),
    ]
